package com.example.classic_bluetooth_demo.util;

public enum ReadMark {
  NONE,
  GET_LABEL_HEIGHT,
  OPERATE_PRINT,//连续纸打印操作
  OPERATE_PRINT_LABEL,//缝隙纸打印操作
  OPERATE_STATUS,//打印机状态查询
  OPERATE_BATVOL,//电量查询
  OPERATE_PRINTERSN,//打印机SN号
  OPERATE_PRINTERMODEL,//打印机型号
  OPERATE_PRINTERVER,//打印机软件版本号
  OPERATE_BTMAC,//蓝牙mac地址
  OPERATE_BTVER,//蓝牙软件版本号
  OPERATE_BTNAME,//蓝牙名称
  OPERATE_INFO,//设备所有信息
  OPERATE_PAPERTYPE,//纸张类型
  OPERATE_TIME,//关机时间
  OPERATE_NFC_PAPER,//纸张信息
  OPERATE_NFC_UID,//标签UID
  OPERATE_NFC_USED_LENGTH,//已使用长度
  OPERATE_NFC_REST_LENGTH,//剩余长度
  OPERATE_WIFI_NAME,//WIFI名称
  OPERATE_WIFI_PASSWORD,//WIFI密码
  OPERATE_WIFI_LINK_STATE,//WIFI连接状态
  OPERATE_WIFI_DHCP,//查询DHCP
  OPERATE_ALL_IP_INFO, //查询IP所有信息
  OPERATE_ALL_WIFI_INFO,//查询WIFI所有信息
  OPERATE_WIFI_ROLE,//WIFI工作模式
  OPERATE_WIFI_APSSID,//AP模式SSID
  OPERATE_WIFI_APPASSWORD,//AP模式密码
  OPERATE_GET_KEY,//查询秘钥
  OPERATE_SET_WIFI,//设置wifi
  OPERATE_SET_KEY,//设置秘钥
  OPERATE_SET_HOST,//设置服务器域名
  // AI打印机专属
  OPERATE_SET_STANDBY_MODE,//设置待机样式
  OPERATE_SET_SYSTEM_LANGUAGE,//设置系统语言
  OPERATE_GET_SYSTEM_LANGUAGE,//获取当前语言
  OPERATE_GET_DEVICE_INFO,//查询设备信息
}
